# Numpy

In [1]:
import numpy as np

## Data Types & Attributes

In [2]:
#ndarray = n dimensional array = main datataype in numpy

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1, 2, 3], (4, 5, 6)])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]],[[4, 5, 6], [1, 2, 3]]])
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 4,  5,  6],
        [ 1,  2,  3]]])

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
x = np.arange(27).reshape((3,3,3))
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
x = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
a1.dtype


dtype('int32')

In [10]:
a1.size

3

In [11]:
type(a1)

numpy.ndarray

## Create DataFrame from a NumPy array

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(a2)

In [14]:
df

0  1  2
0  1  2  3
1  4  5  6

## Creating Arrays


In [15]:
sample_array = np.array([1, 2, 3])

In [16]:
sample_array

array([1, 2, 3])

In [17]:
ones = np.ones((1, 5), dtype = int)

In [18]:
ones

array([[1, 1, 1, 1, 1]])

In [19]:
zeros = np.zeros(5)

In [20]:
zeros

array([0., 0., 0., 0., 0.])

In [21]:
range_array = np.arange(5, 15, 3, dtype = int)
range_array

array([ 5,  8, 11, 14])

In [22]:

random_array = np.random.randint(1, 100, size=(10, 10))
random_array

array([[ 2, 77,  2, 17, 81, 73, 13, 25, 58,  1],
       [12, 22, 57, 98,  4, 54, 48, 77, 50, 35],
       [54, 27, 15, 19, 17, 64, 64, 69,  1, 62],
       [12, 64, 46, 41,  8, 98, 60, 77, 29, 45],
       [29, 28, 93, 79, 90, 26,  5, 94, 31, 83],
       [95, 66, 43,  6,  9, 12, 45, 54, 86, 38],
       [84, 10,  2, 66, 28, 45, 42, 41, 93, 34],
       [74, 97, 29, 72, 28, 19, 91,  6, 90,  4],
       [75, 15, 75, 85, 28, 79, 67, 85, 21, 53],
       [72, 75, 51, 24,  4, 43, 68,  5, 67, 70]])

In [23]:
np.random.random((5, 3))

array([[0.91642931, 0.81392384, 0.82313726],
       [0.29452208, 0.22273448, 0.31679399],
       [0.31690659, 0.91402208, 0.90881371],
       [0.52137259, 0.01946255, 0.46181538],
       [0.88809728, 0.18727102, 0.23752013]])

In [24]:
np.random.rand(5, 3)

array([[0.18087675, 0.09598358, 0.82441117],
       [0.63711432, 0.03920541, 0.45024487],
       [0.329175  , 0.44836427, 0.11448073],
       [0.20029576, 0.55599525, 0.94160856],
       [0.86157427, 0.27452458, 0.24924401]])

In [30]:
# Pseudo-number
np.random.seed(0)
random_array = np.random.randint(15, size=(5, 3))

In [31]:
random_array

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

## Viewing Arrays and Matrices

In [32]:
np.unique(random_array)

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12])

In [33]:
a1[0]

1

In [34]:
a2[0]

array([1, 2, 3])

In [36]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a3[:2, :2, :1]

array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]])

In [38]:
a3.shape

(3, 2, 3)

In [39]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[8, 1, 6, 7, 7],
         [8, 1, 5, 9, 8],
         [9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8]],

        [[1, 3, 3, 3, 7],
         [0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5]],

        [[5, 6, 8, 4, 1],
         [4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5]]],


       [[[9, 4, 4, 6, 4],
         [4, 3, 4, 4, 8],
         [4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3]],

        [[0, 5, 0, 1, 2],
         [4, 2, 0, 3, 2],
         [0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2]],

        [[3, 3, 2, 3, 4],
         [1, 2, 9, 1, 4],
         [6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3]]]])

In [40]:
a4[:, :, :, :1]

array([[[[8],
         [8],
         [9],
         [5]],

        [[1],
         [0],
         [4],
         [2]],

        [[5],
         [4],
         [7],
         [7]]],


       [[[9],
         [4],
         [4],
         [0]],

        [[0],
         [4],
         [0],
         [2]],

        [[3],
         [1],
         [6],
         [0]]]])

## Manipulating Arrays


### Arithmetic

In [44]:
a1

array([1, 2, 3])

In [47]:
ones = np.ones(3, dtype = int)

In [48]:
a1 + ones

array([2, 3, 4])

### Aggregation

Aggregation = performing the same operation on a number of things

In [52]:
my_list = [1, 2, 3]
sum(my_list)

6

In [53]:
sum(a1)

6

In [54]:
np.sum(a1)

6

In [55]:
np.sum(a2)

21

Use Python's  methods `sum()` on Python datatypes and use 
NumPy's methods NumPy arrays `np.sum()`

In [56]:
np.mean(a2)

3.5

In [57]:
np.max(a2)

6

## Reshaping and Transposing

In [60]:
a2 = a2.reshape(3, 2, 1)


In [61]:
a2 * a3

array([[[ 1,  2,  3],
        [ 8, 10, 12]],

       [[21, 24, 27],
        [40, 44, 48]],

       [[20, 25, 30],
        [ 6, 12, 18]]])

In [62]:
a2.T

array([[[1, 3, 5],
        [2, 4, 6]]])

## Dotproduct

In [66]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [67]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [68]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [69]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [70]:
mat1.T


array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [72]:
np.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [75]:
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]])

In [76]:
np.sort(random_array)

array([[2, 3, 8],
       [1, 3, 3],
       [0, 3, 7],
       [1, 9, 9],
       [0, 4, 7]])

In [77]:
np.argsort(random_array)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [79]:
np.argmin(random_array, axis=0), np.argmax(random_array, axis=1)

(array([4, 0, 2], dtype=int64), array([2, 1, 1, 1, 2], dtype=int64))